name: "KiCad GitHub actions"

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '**.kibot.yaml'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '**.kibot.yaml'

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k7
      with:
        # Required - kibot config file
        config: '*.kibot.yaml'
        # optional - prefix to output defined in config
        dir: output
        # optional - schematic file
        schema: '*.kicad_sch'
        # optional - PCB design file
        board: '*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: output
